server:
  port: 9001

spring:
  application:
    name: ceo-service
  datasource:
    url: jdbc:mysql://localhost:3306/ceo?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
